### ISSUE TITLE
deb version incoming?

### ISSUE THREAD

**Issue by IMS212** [lucaIz-ldx/MobileTSS#1]
A deb version would be nice, especially as it could fill out the ecid for you. This would be jailbreak only and the ipa would just be an option for no jailbreak

**Comment by NotHereForTheDong** [comment]
@IMS212 as a work around just download the IPA, unzip in Filza and use these entitlements [https://github.com/Samgisaninja/SuccessionRestore/blob/9041511cc5b44454611ba4f91b35beb603c5f178/SuccessionEntitlements.plist]  and ldid -S /path/to/entitlements.xml /path/to/unzipped/IPAPayloadFolder/*

Ignore any ldid cpp errors as it’s signing all the files when it shouldn’t but just zip the Payload folder to get Payload.zip.  Change to Payload.ipa wit Filza and install with Filza by clicking on the IPA and hitting install

**Comment by lucaIz-ldx** [comment]
I have just released a deb version under release section. Please check it out and report if any issues. Closing it.
